exclude = ["docs/_ext/autodocsumm.py", "src/eradiate/test_tools/benchmark/asvdb.py"]
include = ["pyproject.toml", "src/**/*.py", "tests/**/*.py"]
target-version = "py39"

[lint]
select = [
  "B",
  "C4",
  "E",
  "F",
  "FURB",
  "I",
  "NPY",
  "PERF",
  "PIE",
  "RUF",
  "SIM",
  "UP",
  "W",
]
ignore = [
  "E501",
  "F821",
  "PERF203", # Negligible overhead, try/except in loops is often the clearest form
]
isort = { relative-imports-order = "closest-to-furthest" }
per-file-ignores = { "*.ipynb" = ["E402"] }
allowed-confusables = ["×", "–", "ν", "σ"]
flake8-bugbear = { extend-immutable-calls = [
  "eradiate.attrs.documented",
  "pinttrs.field",
] }
