from __future__ import annotations

from typing import Tuple

import mitsuba as mi
import pytest

from ..contexts import KernelContext
from ..kernel import KernelDictionary, mi_traverse
from ..scenes.core import CompositeSceneElement, NodeSceneElement


# TODO: Polish
def check_scene_element(
    instance: NodeSceneElement | CompositeSceneElement,
    mi_cls: type,
    ctx: KernelContext | None = None,
) -> Tuple["mitsuba.Object", "mitsuba.SceneParameters"]:
    """
    Perform kernel dictionary checks on a scene element.

    This function checks if the scene element can produce a valid kernel
    dictionary template, as well as an appropriate parameter table.

    The returned Mitsuba object and parameter table can be used to perform
    additional checks.

    Parameters
    ----------
    instance : :class:`.NodeSceneElement` or :class:`.CompositeSceneElement`
        Node scene element to check.

    mi_cls : type
        Mitsuba class the node scene element expands to. Must be set if
        `instance` is a :class:`.NodeSceneElement`; ignored otherwise.

    ctx : .KernelContext, optional
        If provided, the kernel dictionary context to use. Otherwise, a default
        context is created.

    Returns
    -------
    mi_obj : mitsuba.Object
        Mitsuba object the scene element was expanded to. See notes for details.

    mi_params : dict
        Parameter table of the Mitsuba objects generated by the tested scene
        element.

    Notes
    -----
    * If `instance` is a :class:`.NodeSceneElement`, the corresponding Mitsuba
      object type is checked against `mi_cls`.
    * If `instance` is a :class:`.CompositeSceneElement`, the corresponding
      Mitsuba objects are automatically encapsulated into a
      :class:`mitsuba.Scene` object.
    """
    if isinstance(instance, NodeSceneElement):
        if mi_cls is None:
            raise ValueError("Expected Mitsuba class must be set")
        kdict_template = instance.kdict()
        kpmap_template = instance.kpmap()

    elif isinstance(instance, CompositeSceneElement):
        mi_cls = mi.Scene
        kdict_template = KernelDictionary({"type": "scene", **instance.kdict()})
        kpmap_template = instance.kpmap()

    else:
        raise RuntimeError(f"Cannot test type '{instance.__class__}'")

    # Check if the template can be instantiated
    ctx = KernelContext() if ctx is None else ctx
    kdict = kdict_template.render(ctx)

    try:
        mi_obj = mi.load_dict(kdict)
    except RuntimeError as e:
        pytest.fail(
            reason=f"could not load scene dictionary, got RuntimeError: {e}\n"
            f"{kdict = }"
        )

    assert isinstance(mi_obj, mi_cls)

    # Collect Mitsuba parameters
    mi_params = mi_traverse(mi_obj)

    # Check that parameters can all be set
    kpmap = kpmap_template.render(ctx)
    for key, value in kpmap.items():
        try:
            mi_params[key] = value
        except KeyError as e:
            pytest.fail(
                reason=f"could not set parameter, got KeyError: {e}\n{mi_params = }"
            )
    mi_params.update()

    return mi_obj, mi_params
